import { GoogleAnalytics } from "@next/third-parties/google";
import { type Metadata } from "next";
import { type JSX, type ReactNode } from "react";
import { NavigationProgressBar } from "~/components/navigation-progress-bar";
import { getConfig } from "~/helpers/config";
import { baseFont } from "~/helpers/fonts";
import "../variables.css";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL("https://www.axross.dev"),
  title: "axross.dev",
  description: "Generated by create next app",
};

function Layout({ children }: { readonly children: ReactNode }): JSX.Element {
  const config = getConfig();

  return (
    <html lang="en">
      <body className={baseFont.className}>
        {children}

        <NavigationProgressBar />
      </body>

      <GoogleAnalytics gaId={config.googleAnalytics.measurementId} />
    </html>
  );
}

export default Layout;
