import { type Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { type JSX, type ReactNode } from "react";

// eslint-disable-next-line new-cap
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Layout({ children }: { readonly children: ReactNode }): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

export default Layout;
