name: Check to Merge
on:
  push:
    branches:
      - "*"
      - "!master"
jobs:
  dry-compile:
    name: Dry Compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - run: npm ci
      - run: npm run dry-compile
  unit-test:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - run: npm ci
      - run: npm run test-unit -- --ci --coverage
  visual-test:
    name: Visual Regression Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - run: npm ci
      - run: npm run test-visual -- --ci
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: Visual Regression Test Diffs
          path: storyshots/__image_snapshots__/__diff_output__
  dry-build:
    name: Dry Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - run: npm ci
      - run: npm run build
        env:
          CONTENTFUL_SPACE: ${{ secrets.CONTENTFUL_SPACE }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
      - run: npm run build-storybook
        env:
          CONTENTFUL_SPACE: ${{ secrets.CONTENTFUL_SPACE }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
