name: Check to Merge
on:
  push:
    branches:
      - "*"
jobs:
  dry-compile:
    name: Dry Compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - run: npm ci
      - run: npm run dry-compile
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - run: npm ci
      - run: npm test
