name: "E2E Test"
on: [pull_request]
jobs:
  e2e-test:
    name: E2E Test
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA: e2e-test
      NEXT_PUBLIC_GRAPHCMS_ENDPOINT: ${{ secrets.E2E_GRAPHCMS_ENDPOINT }}
      NEXT_PUBLIC_SIMPLE_LOCALIZE_TOKEN: ${{ secrets.E2E_SIMPLE_LOCALIZE_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: microsoft/playwright-github-action@v1
      - name: Install dependencies
        run: npm ci
      - name: Run E2E tests
        run: npx start-server-and-test "npm run build && npx next start" "http://localhost:3000" "npm run e2e-test -- --ci --verbose"
