name: I18n Dictionary Download
on:
  repository_dispatch:
    types:
      - simplelocalize_publication
jobs:
  download-and-apply:
    name: Dictionary Download
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download dictionary files from SimpleLocalize
        uses: simplelocalize/github-action-cli@v2
        with:
          cli-version: 2.5.1
          command: download
          args: --downloadFormat=single-language-json --downloadPath=./src/locales/{lang}/{ns}.json
          api-key: ${{ secrets.SIMPLELOCALIZE_API_KEY }}
      - name: Upload the parsed dictionary files as artifacts
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git switch -c i18n-update-${{ github.run_id }}
          git add .
          git commit -m "feat(i18n): apply i18n dictionary update(s)"
          git push origin i18n-update-${{ github.run_id }}
      - name: Create a pull request
        run: |
          gh pr create \
            --base main \
            --head i18n-update-${{ github.run_id }} \
            --assignee @me \
            --title "feat(i18n): apply i18n dictionary update(s)"
            --reviewer @axross
        env:
          GH_TOKEN: ${{ github.token }}
